### ISSUE TITLE
[BUG]aMap registration only in cellfinder with window10

### ISSUE THREAD

**Issue by zhiwen10** [SainsburyWellcomeCentre/cellfinder#106] opened 2020-05-07 07:02 UTC
Hi Adam,
Thank you for releasing the cellfinder version with Window support.
I'm trying to only register a brain sample that was already downsampled to isotropic 10um resolution, but error was reported in windows 10.
1, Basic testing with only detection worked fine, with a .xml file output with candidate cell coordinates.
`cellfinder -s "C:\Users\Steinmetz lab\Documents\amap_data\ERAE23_3c" -b "C:\Users\Steinmetz lab\Documents\amap_data\ERAE23_3c" -o "C:\Users\Steinmetz lab\Documents\amap_data\ERAE23_3c_output" -x 10 -y 10 -z 10 --no-classification`
2, aMap registration only, failed with error message.
`cellfinder -s "C:\Users\Steinmetz lab\Documents\amap_data\ERAE23_3c" -b "C:\Users\Steinmetz lab\Documents\amap_data\ERAE23_3c" -o "C:\Users\Steinmetz lab\Documents\amap_data\ERAE23_3c_output" -x 10 -y 10 -z 10 --flip-x --register --no-detection --no-classification`

2020-05-06 23:59:20 PM - INFO - MainProcess fancylog.py:265 - Starting logging
Traceback (most recent call last):
2020-05-06 23:59:20 PM - INFO - MainProcess fancylog.py:267 - Multiprocessing-logging module found. Logging from all processes
  File "c:\users\steinmetz lab\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
2020-05-06 23:59:20 PM - INFO - MainProcess main.py:32 - Registering to atlas
    "__main__", mod_spec)2020-05-06 23:59:20 PM - INFO - MainProcess prep.py:401 - Checking whether the atlas exists

  File "c:\users\steinmetz lab\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Steinmetz lab\AppData\Local\Programs\Python\Python37\Scripts\cellfinder.exe\__main__.py", line 7, in <module>
  File "c:\users\steinmetz lab\appdata\local\programs\python\python37\lib\site-packages\cellfinder\main.py", line 61, in main
    debug=args.debug,
  File "c:\users\steinmetz lab\appdata\local\programs\python\python37\lib\site-packages\amap\main.py", line 93, in main
    registration_config, dest_folder=Path(registration_output_folder)
  File "c:\users\steinmetz lab\appdata\local\programs\python\python37\lib\site-packages\amap\config\atlas.py", line 25, in __init__
    super().__init__(config_path)
  File "c:\users\steinmetz lab\appdata\local\programs\python\python37\lib\site-packages\neuro\atlas\atlas_class.py", line 24, in __init__
    atlas_id = list(data_dict.keys())[0]  # assume only one key
IndexError: list index out of range

Any ideas why this happened? I have ran "cellfinder_download" before hand to download atlas to default folders.

**Comment by vigji** [comment] 2020-05-07 07:43
I see it's failing in the Atlas class, but I don't think the problem's there as tests were fine; it looks like a configuration file is not found. Do you have a `config.conf` file in `C:\Users\Steinmetz lab\Documents\amap_data\ERAE23_3c`?

**Comment by zhiwen10** [comment] 2020-05-07 07:50
Hi Luigi, `config.conf`  is missing in `C:\Users\Steinmetz lab\Documents\amap_data\ERAE23_3c`.

**Comment by vigji** [comment] 2020-05-07 08:19
But do you have there the atlas folder? `allen_2017_100um`

**Comment by adamltyson** [comment] 2020-05-07 08:24
Hi Zhiwen,

What is your input data, a series of tiffs, or a single multipage tiff etc?

Is this brainsaw data?

Adam

**Comment by zhiwen10** [comment] 2020-05-07 08:25
Atlas folder was generated by `cellfinder_download` into a default folder before running cellfinder command: user\cellfinder\atlas\allen_2017_10um. Atlas folder is not present under `C:\Users\Steinmetz lab\Documents\amap_data\ERAE23_3c`. This folder is where raw sample tiff files (and only raw tiff files) are stored.

**Comment by zhiwen10** [comment] 2020-05-07 08:26
Hi Adam, input data is a series of tiffs.

**Comment by adamltyson** [comment] 2020-05-07 08:27
What happens if you run amap directly (`amap  "C:\Users\Steinmetz lab\Documents\amap_data\ERAE23_3c" "C:\Users\Steinmetz lab\Documents\amap_data\ERAE23_3c_output" -x 10 -y 10 -z 10 `)?

**Comment by zhiwen10** [comment] 2020-05-07 08:41
I ran amap directly, it is working (loading iamges, etc). It did complain about 'root: Atlas does not exist, downloading'. Took a while to download, then working fine. Guess it didn't find the location of Atlas in cellfinder.  Any workaround in cellfinder?

**Comment by adamltyson** [comment] 2020-05-07 08:50
There's an issue that amap and cellfinder don't work properly together, so it will download two versions of the atlas (one at `~/.amap` and one at `~/.cellfinder`). If you want to prevent these both from existing, you should be able to delete the `~/.amap` directory and then run `amap_download --install-path ~/.cellfinder/atlas` (or the Windows equivalent) to link them.

I'm not sure why registration in cellfinder isn't working properly, I'll look into it.

We should also add this to the tests (https://github.com/SainsburyWellcomeCentre/cellfinder/issues/93)

**Comment by adamltyson** [comment] 2020-05-07 09:38
@zhiwen10 I don't seem to be having any issue locally with some of my data. Is it possible for you to share your data for me to test?

I'm also release a new release candidate (`pip install cellfinder==0.3.13rc0 --upgrade`) that should be out in about 30 mins. This is the same as the current master, so would be good to diagnose.

Could you also send me the output of `conda list` (assuming you're using conda)?

**Comment by zhiwen10** [comment] 2020-05-07 09:47
Okay, I ran unto another issue in amap, complaining space in my path, which reminded me of an issue during installation in cellfinder. 
`(cellfinder) c:\>pip install cellfinder`
`Unable to create process using 'C:\Users\Steinmetz lab\.conda\envs\cellfinder\python.exe "C:\Users\Steinmetz lab\.conda\envs\cellfinder\Scripts\pip-script.py" install cellfinder'`
I then deactivated cellfinder, and pip installed cellfinder. So I was not running cellfinder in conda environment. Sorry, I need to reinstall my miniconda in a different path without empty space. Might just be that.

**Comment by adamltyson** [comment] 2020-05-07 09:56
If you could do a fresh install of `cellfinder==0.3.13rc0` that would be awesome to fully test everything.

**Comment by zhiwen10** [comment] 2020-05-07 11:15
Hey, it took me a while to fix the path problem in this windows PC, amap is working fine. After successful reinstallation of cellfinder, same error message appeared. Data is here (import using imageJ, then save as image sequences): [https://drive.google.com/file/d/1XLxjZ0toLPFeMHLIKpBhLR8evyejIERF/view?usp=sharing]. 

Also installed in a separate laptop, same error message, after upgrade as well. Conda lists: [https://docs.google.com/document/d/1Ez4JErceiXkc4w1t0jxipuOE9gcKF1qkAdoRabdgp5k/edit?usp=sharing]
[https://docs.google.com/document/d/1IbXd7azxpHqKhtss--6F-0JWQcy6vCURj2YUXTdKxBw/edit?usp=sharing].

**Comment by zhiwen10** [comment] 2020-05-07 12:21
Restriction for the link should be removed now. Sorry about that.

**Comment by adamltyson** [comment] 2020-05-07 15:17
Hi Zhiwen,

I tested this out on my machine (Linux, and it seems to work fine), and registration is ok:
![zhiwen_cellfinder_reg](https://user-images.githubusercontent.com/13147259/81311861-d1990680-907d-11ea-9faf-898612b965db.png)


I downloaded your `.nii` file, rotated it 90 degrees to be the right way up and saved as a tiff series (in FIJI), then ran:
```bash
cellfinder -s /media/adam/Storage/cellfinder/data/zhiwen_tif_export_rotated -b /media/adam/Storage/cellfinder/data/zhiwen_tif_export_rotated -o /media/adam/Storage/cellfinder/analysis/zhiwentest --debug -x 10 -y 10 -z 10 --n-free-cpus 6 --register --no-detection --no-classification
```

Could you have a go at doing this?

**Comment by zhiwen10** [comment] 2020-05-07 18:21
Ok, it took me a while to figure out the right orientation to feed into amap, but finally got it right as you suggested too. Then I tried cellfinder with the correct oriented data, it is working without complaining error.

**Comment by adamltyson** [comment] 2020-05-07 18:27
Cool, I need to document the orientation stuff better. 

Glad it’s working for you. Let me know if you have any other issues. 

There’s also the [gitter channel](https://gitter.im/cellfinder/) for general questions.

**Comment by zhiwen10** [comment] 2020-05-08 06:09
Thanks! i can see the windows version super useful where powerful hardware and linux system is not available. 
More documentation on the orientation would certainly help. Or if there is example data available to download for testing for beginners, that would be super informative! Also, the error message with the wrong orientation could be more specific, instead of the one that shown above (Just a suggestion). Somehow, amap python did not complain about this error even with wrong orientation, and I managed to get output with amap with wrong orientation, through really stretched and tilted registration.

**Comment by adamltyson** [comment] 2020-05-08 06:15
Thanks Zhiwen. Definitely need to provide example data, and also try to improve some of the error messages. 


Reopening this so I’ll take a look at why cellfinder threw an error but amap didn’t.

**Comment by adamltyson** [comment] 2020-06-30 15:00
Closing this as I can't seem to reproduce. @zhiwen10 feel free to reopen if this occurs again.

**Closed by adamltyson** 2020-06-30 15:00 UTC
Labels: HIGH PRIORITY, bug
