### ISSUE TITLE
[BUG] IndexError: list index out of range while  Loading raw image data

### ISSUE THREAD

**Issue by FedeClaudi** [SainsburyWellcomeCentre/cellfinder#27] opened 2020-01-29 20:03 UTC
**Describe the bug**
Cellfinder yields an `IndexError` while loading raw images from a list of file paths. [While running on the HPC cluster and fetching data from winstor]

From the Log file:
```
**************  COMMAND LINE ARGUMENTS  **************

Command: /nfs/nhome/live/federicoc/.conda/envs/cellfinder/bin/cellfinder
Input arguments: ['-s', '/nfs/winstor/branco/BrainSaw/AY_246_4/stitchedImages_100/3', '/nfs/winstor/branco/BrainSaw/AY_246_4/stitchedImages_100/2', '-b', '/nfs/winstor/branco/BrainSaw/AY_246_4/stitchedImages$

...


**************  LOGGING  **************

2020-01-29 18:17:50 PM - INFO - MainProcess fancylog.py:257 - Starting logging
2020-01-29 18:17:50 PM - INFO - MainProcess fancylog.py:259 - Multiprocessing-logging module found. Logging from all processes
2020-01-29 18:17:50 PM - INFO - MainProcess main.py:32 - Registering to atlas
2020-01-29 18:17:50 PM - INFO - MainProcess prep.py:398 - Checking whether the atlas exists
2020-01-29 18:17:50 PM - DEBUG - MainProcess prep.py:417 - Making registration directory
2020-01-29 18:17:50 PM - DEBUG - MainProcess system.py:111 - Determining the maximum number of CPU cores to use
2020-01-29 18:17:50 PM - DEBUG - MainProcess system.py:120 - Number of CPU cores available is: 8
2020-01-29 18:17:50 PM - DEBUG - MainProcess system.py:145 - Setting number of processes to: 8
2020-01-29 18:17:50 PM - INFO - MainProcess main.py:85 - Preprocessing data for registration
2020-01-29 18:17:50 PM - INFO - MainProcess main.py:86 - Loading data
2020-01-29 18:17:50 PM - INFO - MainProcess batteryrunners.py:274 - pixdim[0] (qfac) should be 1 (default) or -1; setting qfac to 1
2020-01-29 18:17:50 PM - INFO - MainProcess brain_processor.py:79 - Loading raw image data
2020-01-29 18:17:50 PM - DEBUG - MainProcess brainio.py:72 - Data type is: directory of files
2020-01-29 18:17:53 PM - DEBUG - MainProcess utils.py:104 - Determining the maximum number of CPU cores to use
2020-01-29 18:17:53 PM - DEBUG - MainProcess utils.py:116 - Setting number of processes to: 8
```

Complete error message:
```
"""
Traceback (most recent call last):
  File "/nfs/nhome/live/federicoc/.conda/envs/cellfinder/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/nfs/nhome/live/federicoc/.conda/envs/cellfinder/lib/python3.7/site-packages/brainio/brainio.py", line 304, in load_from_paths_sequence
    img = tifffile.imread(p)
  File "/nfs/nhome/live/federicoc/.conda/envs/cellfinder/lib/python3.7/site-packages/tifffile/tifffile.py", line 716, in imread
    return tif.asarray(**kwargs)
  File "/nfs/nhome/live/federicoc/.conda/envs/cellfinder/lib/python3.7/site-packages/tifffile/tifffile.py", line 2373, in asarray
    series = self.series[series]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nfs/nhome/live/federicoc/.conda/envs/cellfinder/bin/cellfinder", line 8, in <module>
    sys.exit(main())
  File "/nfs/nhome/live/federicoc/.conda/envs/cellfinder/lib/python3.7/site-packages/cellfinder/main.py", line 61, in main
    debug=args.debug,
  File "/nfs/nhome/live/federicoc/.conda/envs/cellfinder/lib/python3.7/site-packages/amap/main.py", line 98, in main
    n_free_cpus=n_free_cpus,
  File "/nfs/nhome/live/federicoc/.conda/envs/cellfinder/lib/python3.7/site-packages/amap/register/brain_processor.py", line 87, in __init__
    n_free_cpus=n_free_cpus,
  File "/nfs/nhome/live/federicoc/.conda/envs/cellfinder/lib/python3.7/site-packages/brainio/brainio.py", line 79, in load_any
    n_free_cpus=n_free_cpus,
  File "/nfs/nhome/live/federicoc/.conda/envs/cellfinder/lib/python3.7/site-packages/brainio/brainio.py", line 190, in load_from_folder
    paths, x_scaling_factor, y_scaling_factor, n_free_cpus=n_free_cpus
  File "/nfs/nhome/live/federicoc/.conda/envs/cellfinder/lib/python3.7/site-packages/brainio/brainio.py", line 279, in threaded_load_from_sequence
    stack = np.dstack([s.result() for s in stacks])
  File "/nfs/nhome/live/federicoc/.conda/envs/cellfinder/lib/python3.7/site-packages/brainio/brainio.py", line 279, in <listcomp>
    stack = np.dstack([s.result() for s in stacks])
  File "/nfs/nhome/live/federicoc/.conda/envs/cellfinder/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/nfs/nhome/live/federicoc/.conda/envs/cellfinder/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
IndexError: list index out of range
```

**Comment by adamltyson** [comment] 2020-01-29 20:08
Could you post the full log file?

**Comment by FedeClaudi** [comment] 2020-01-29 20:18
[cellfinder_2020-01-29_18-17-50.log](https://github.com/SainsburyWellcomeCentre/cellfinder/files/4130498/cellfinder_2020-01-29_18-17-50.log)

The same happened for another couple instances of cell finder, for instance:
[cellfinder_2020-01-29_18-17-45.log](https://github.com/SainsburyWellcomeCentre/cellfinder/files/4130501/cellfinder_2020-01-29_18-17-45.log)

These are data that I analysed before (just running again to look at the effect of changing the soma size argument), so not sure why this time it went wrong. I'm running it again, will keep you posted.

**Comment by adamltyson** [comment] 2020-01-30 11:36
Strange, It's failing during loading data for registration, but you haven't changed any registration parameters.

We did used to see a similar issue on the cluster, when the server was automatically unmounted, but I think that's fixed. 

I can't reproduce this locally. but I'll try on the cluster. Depending on your enthusiasm there are some other things that can be tried:
* Check none of the files in the background signal directory are corrupted, or renamed etc.
* Try running it again with the data somewhere else (e.g. scratch).

**Comment by FedeClaudi** [comment] 2020-01-30 11:40
Files are not corrupted or renamed, I'm copying the data locally for testing. 

The weird thing is that:
     1. I've analysed these data without any problem
     2. Running the same script on another dataset doesn't cause any problem.

**Comment by adamltyson** [comment] 2020-01-30 11:42
This is why I think it could possibly be something like a specific network issue. Does cellfinder find the data if you skip registration?

**Comment by adamltyson** [comment] 2020-02-22 09:37
@FedeClaudi has this happened since?

**Comment by adamltyson** [comment] 2020-03-01 14:34
Closing as I haven't been able to replicate. @FedeClaudi feel free to reopen.

**Closed by adamltyson** 2020-03-01 14:34 UTC
Labels: bug
