### ISSUE TITLE
[BUG] Cellfinder 2D viewer not working on windows

### ISSUE THREAD

**Issue by FedeClaudi** [SainsburyWellcomeCentre/cellfinder#26] opened 2020-01-29 17:21 UTC
**Describe the bug**
The [2D viewer](https://sainsburywellcomecentre.github.io/cellfinder/main/user_guide/tools/cell_view_2D.html) to inspect the results of cellfinder doesn't start on windows [gets stuck while loading the data].

**Comment by adamltyson** [comment] 2020-01-30 15:12
Thanks to @FedeClaudi, this seems to be related to https://github.com/napari/napari/issues/733. Should be an easy workaround.

**Comment by FedeClaudi** [comment] 2020-01-30 15:13
As per the issue above:

Calling   `v.add_image(images, contrast_limits =[0.0, 1000.0])` works, 
The upper bound of the contrast limits should be computed for each dataset though.

**Comment by adamltyson** [comment] 2020-01-30 15:15
Thanks. 
Temporary fix could be:
* Compute histogram on "some" images (e.g. every nth, or the middle n)
* Calculate a "liberal" limit (e.g. 0->max*2)
* `v.add_image` with these contrast limits

**Comment by adamltyson** [comment] 2020-01-30 15:15
Alternatively, just pass the "theoretical" max from `dtype` and allow the user to change the limits. This is probably not ideal though.

**Comment by adamltyson** [comment] 2020-02-03 16:14
N.B. If this issue persists, it will need fixing for the curation interface too.

**Comment by FedeClaudi** [comment] 2020-02-03 17:24
Can confirm that the same problem comes up with curation interface.

**Comment by adamltyson** [comment] 2020-02-11 14:11
Fixed in a62766104e2c503ac911c1c90e3ca547a9367835.

Not sure if this should be made smarter though. Currently it just takes 2x max of the middle slice.

**Comment by sofroniewn** [comment] 2020-03-14 04:45
@FedeClaudi @adamltyson I'm trying to chase down and eliminate any remaining contrast limit estimation bugs so that if users don't explicitly pass `contrast_limits` we don't choke. Can you confirm if you're still having any issues if you don't pass `contrast_limits` with the `0.2.12` napari release.

**Comment by sofroniewn** [comment] 2020-03-14 05:11
> Compute histogram on "some" images (e.g. every nth, or the middle n)

This is now the approach napari employs - see https://github.com/napari/napari/blob/master/napari/layers/layer_utils.py#L25-L65 - it would be good to know if we are failing still

**Comment by adamltyson** [comment] 2020-03-14 13:45
@sofroniewn I couldn't replicate this issue, @FedeClaudi is this something you can test? Perhaps by loading raw data into the amap viewer (assuming you can actually access your data currently)?

I'd like to remove my hacky fix and rely on napari dealing with this more gracefully if possible.

**Comment by adamltyson** [comment] 2020-04-28 09:55
Looks to be working (eda3c1097f4a309664b391b4993a3e60f166c2c5), but I could never fully reproduce this.

**Closed by adamltyson** 2020-04-28 09:55 UTC
Labels: HIGH PRIORITY, bug
